### ISSUE TITLE
能给一个蓝图模式的example嘛？

### ISSUE THREAD

**Issue by sunhailin-Leo** [Sanic-Extensions/sanic-mail#1]
如题：能给一个蓝图模式的example嘛？

我试了几个方法都是报： AttributeError: 'NoneType' object has no attribute 'send_message'

启动py文件配置：
![_20180329203204](https://user-images.githubusercontent.com/17564655/38088982-73feccb8-3390-11e8-929a-f475c59264c8.png)

蓝图里面的方法：
![_20180329203207](https://user-images.githubusercontent.com/17564655/38088986-79298250-3390-11e8-9934-04c9672eae32.png)

**Comment by sunhailin-Leo** [comment]
![_20180329204606](https://user-images.githubusercontent.com/17564655/38089500-35f6e976-3392-11e8-85ee-2a3e8fe81e9f.png)

我用Restclient测试就发现在 smtp的对象一直是空值
即使把 初始化的形式用第一种， 即不调用init_app也是空值

**Comment by sunhailin-Leo** [comment]
![_20180329210513](https://user-images.githubusercontent.com/17564655/38090360-e5207e1a-3394-11e8-892f-f328c91a3987.png)
![_20180329210516](https://user-images.githubusercontent.com/17564655/38090362-e5e4d1de-3394-11e8-84b0-06f7b9355671.png)

我另起了一个项目测试，依旧不行。
sender变量是null

代码如上图~ 

Hope Fix it

**Comment by sunhailin-Leo** [comment]
找到问题所在了 :flushed: 

我把这段话理解成 Sanic_Mail对象在蓝图里面初始化 --> [Here](https://github.com/Sanic-Extensions/sanic-mail#发送)

**Comment by hsz1273327** [comment]
欸.....这个....感谢关注.....额...我最近做东西邮箱堆了100+封没注意到有工单....晚上回去把文档写写清楚.....不好意思哇
